apiVersion: v1
kind: Service
metadata:
  name: login-app-service
  labels:
    app: login-app
spec:
  type: NodePort  # Use NodePort for minikube access
  selector:
    app: login-app
    strategy: rolling
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    # nodePort: 30080  # Optional: specify a fixed port (30000-32767 range)