apiVersion: v1
kind: Service
metadata:
  name: login-app-canary
  labels:
    app: login-app
    track: canary
spec:
  type: ClusterIP
  selector:
    app: login-app
    track: canary
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http