apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: login-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: login-app-stable
            port:
              number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-app-canary
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: nginx
  rules:
  - host: login-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: login-app-canary
            port:
              number: 5000