apiVersion: v1
kind: Service
metadata:
  name: login-app-stable
  labels:
    app: login-app
    track: stable
spec:
  type: ClusterIP
  selector:
    app: login-app
    track: stable
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http